services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elastic
    environment:
    - discovery.type=single-node
##    - bootstrap.memory_lock=true
    - xpack.security.enabled=true
    - ES_JAVA_OPTS=-Xmx2g -Xms2g
    - ELASTIC_PASSWORD=fusion
    - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:8.17.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

  db:
    image: postgres:17.2
    container_name: postgres-db
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - search_service_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: fusion
      POSTGRES_DB: search-service-db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  search_service_data:
#  kafka_data:



