services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elastic
    environment:
    - discovery.type=single-node
##    - bootstrap.memory_lock=true
#    - xpack.security.enabled=false
##    - ES_JAVA_OPTS=-Xmx2g -Xms2g
#    - ELASTIC_PASSWORD=fusion
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana:8.16.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

  db:
    image: postgres:17.2
    container_name: postgres-db
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: fusion
      POSTGRES_DB: elastic-db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  postgres_data:



